# you can add and choose themes from the ~/.config/kitty/themes/
include themes/monochrome&red.conf

# reload config live
auto_reload_config 0.1

# Show kitty Documentation
map ctrl+shift+f1 show_kitty_doc overview

# shell settings
# works with zsh,fish and bash
shell_integration enabled

# Default

# replaced the . by your preferences
shell .

editor .

# font settings
font_family JetBrainsMono Nerd Font Bold
font_size 11.0
bold_font auto

# background settings
background_opacity 0.85
dynamic_background_opacity 1
confirm_os_window_close 0

# cursor settings
cursor_trail 2
cursor_trail_decay 0.03 0.07

cursor_shape

progress_bar bottom

# URL settings
detect_urls yes

# tab settings

enabled_layours tall:bias=50

# alignment of tab bar, can be : start, center, end, left, right.
tab_bar_align center

# tab bar style, can be : fade (see also tab_fade), slant, separator (see also tab_separator), powerline (see also tab_powerline_style), hidden, custom (see https://github.com/kovidgoyal/kitty/discussions/4447 for exemples from kitty users)
tab_bar_style separator

# tab_fade 0.25 0.5 0.75 1

 tab_separator " / "

# can be one of: angled, slanted, round
# tab_powerline_style slanted
