# you can add and choose themes from the ~/.config/kitty/themes/
include themes/monochrome.conf

# font settings
font_family JetBrainsMono Nerd Font Bold
font_size 11.0
bold_font auto

# background settings
background_opacity 0.80
dynamic_background_opacity 1
confirm_os_window_close 0

# cool animation on the trail
cursor_trail 2
