# black
color0 #hex-color
color8 #hex-color

# red
color1 #hex-color
color9 #hex-color

# green
color2 #hex-color
color10 #hex-color

# yellow
color3 #hex-color
color11 #hex-color

# blue
color4 #hex-color
color12 #hex-color

# magenta
color5 #hex-color
color13 #hex-color

# cyan
color6 #hex-color
color14 #hex-color

# white
color7 #hex-color
color15 #hex-color

cursor                #hex-color
cursor_text_color     #hex-color
background            #hex-color
foreground            #hex-color
selection_foreground  #hex-color
selection_background  #hex-color
active_border_color   #hex-color
inactive_border_color #hex-color

url_color             #hex-color
# url_style

# tab color
tab_bar_margin_color #hex-color

# active tab color settings
active_tab_foreground   #hex-color
active_tab_background   #hex-color

# inactive tab color settings
inactive_tab_foreground #hex-color
inactive_tab_background #hex-color

cursor_trail_color      #hex-color
