# black
color0 #474747
color8 #919191

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2 #ffffff
color10 #ffffff

# yellow
color3 #ABF7FF
color11 #ABF7FF

# blue
color4 #ffb4ab
color12 #e2e2e2

# magenta
color5 #7d7d7d
color13 #7d7d7d

# cyan
color6 #ababab
color14 #ababab

# white
color7 #e2e2e2
color15 #e2e2e2

cursor                #ffb4ab
cursor_text_color     #ffb4ab
background            #000000
foreground            #e2e2e2
selection_foreground  #ffb4ab
selection_background  #474747
active_border_color   #ffffff
inactive_border_color #3a3a3a

url_color             #ffb4ab
# url_style

# active tab color settings
active_tab_foreground   #ffb4ab
active_tab_background   #3a3a3a
# inactive tab color settings
inactive_tab_foreground #e2e2e2
inactive_tab_background #3a3a3a

cursor_trail_color      #ffb4ab
