# black
color0 #474747
color8 #919191

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2 #ffffff
color10 #ffffff

# yellow
color3 #ffb4ab
color11 #ffb4ab

# blue
color4 #ffb4ab
color12 #e2e2e2

# magenta
color5 #ffb4ab
color13 #7d7d7d

# cyan
color6 #ffffff
color14 #ffb4ab

# white
color7 #e2e2e2
color15 #e2e2e2

cursor                #ffb4ab
cursor_text_color     #ffb4ab
background            #000000
foreground            #e2e2e2
selection_foreground  #ffb4ab
selection_background  #474747
active_border_color   #ffffff
inactive_border_color #ffb4ab

url_color             #F7FFAB
# url_style

# tab color
tab_bar_margin_color #ffb4ab

# active tab color settings
active_tab_foreground   #ffb4ab
active_tab_background   #1C1C1C

# inactive tab color settings
inactive_tab_foreground #e1e1e1
inactive_tab_background #121212

cursor_trail_color      #ffb4ab
