color0 #26252c
color1 #fd4663
color2 #7a74f2
color3 #ab64dc
color4 #ce6bc8
color5 #9893ec
color6 #c796e9
color7 #f2f2f3
color8 #666673
color9 #fd4663
color10 #7a74f2
color11 #ab64dc
color12 #ce6bc8
color13 #9893ec
color14 #c796e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #000000
background            #000000
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #26252c
active_border_color   #6f67e4
inactive_border_color #100f16
url_color             #6f67e4

active_tab_foreground   #090713
active_tab_background   #6f67e4
inactive_tab_foreground #afafb6
inactive_tab_background #100f16
cursor_trail_color      #afafb6
