color0 #083349
color1 #fd4663
color2 #4dc3ff
color3 #5c84ff
color4 #9175ff
color5 #80d4ff
color6 #8093ff
color7 #f2f2f3
color8 #657075
color9 #fd4663
color10 #4dc3ff
color11 #5c84ff
color12 #9175ff
color13 #80d4ff
color14 #8093ff
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #000000
background            #000000
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #083349
active_border_color   #4dc3ff
inactive_border_color #00131f
url_color             #4dc3ff

active_tab_foreground   #182125
active_tab_background   #4dc3ff
inactive_tab_foreground #afb4b6
inactive_tab_background #00131f
cursor_trail_color      #afb4b6
